
// This file has been generated by the GUI designer. Do not modify.
namespace ToDoList.Forms
{
	public partial class EditToDoItem
	{
		private global::Gtk.VBox vbox;

		private global::Gtk.Label DescriptionLabel;

		private global::Gtk.Label DescriptionError;

		private global::Gtk.Entry Subject;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView Description;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ToDoList.Forms.EditToDoItem
			this.Name = "ToDoList.Forms.EditToDoItem";
			this.Title = global::Mono.Unix.Catalog.GetString("EditToDoItem");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ToDoList.Forms.EditToDoItem.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this.DescriptionLabel = new global::Gtk.Label();
			this.DescriptionLabel.Name = "DescriptionLabel";
			this.DescriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Description");
			this.vbox.Add(this.DescriptionLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox[this.DescriptionLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.DescriptionError = new global::Gtk.Label();
			this.DescriptionError.Name = "DescriptionError";
			this.DescriptionError.LabelProp = global::Mono.Unix.Catalog.GetString("Description Error");
			this.vbox.Add(this.DescriptionError);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox[this.DescriptionError]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.Subject = new global::Gtk.Entry();
			this.Subject.CanFocus = true;
			this.Subject.Name = "Subject";
			this.Subject.IsEditable = true;
			this.Subject.InvisibleChar = '•';
			this.vbox.Add(this.Subject);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox[this.Subject]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.Description = new global::Gtk.TextView();
			this.Description.CanFocus = true;
			this.Description.Name = "Description";
			this.GtkScrolledWindow.Add(this.Description);
			this.vbox.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox[this.GtkScrolledWindow]));
			w5.Position = 3;
			this.Add(this.vbox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 416;
			this.DefaultHeight = 300;
			this.DescriptionError.Hide();
			this.Show();
			this.Subject.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.OnEntry2KeyReleaseEvent);
			this.Description.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.OnDescriptionKeyReleaseEvent);
		}
	}
}
